name: 'Setup cache'
description: 'Setup, retrieve cache'
author: 'okta'

inputs:
  pod-path:
    description: 'Path to Pods'
    required: true
  lock-hash: 
    # We should pass a full hash because `hashFiles('${{ inputs.lock-path }}/yarn.lock')` doesn't work
    description: 'Hash of Podfile.lock'
    required: true

outputs:
  cache-hit:
    description: "Cache Pods succeeded"
    value: ${{ steps.pods-node.outputs.cache-hit }}

runs:
  using: "composite"
  steps:
  - name: Cache CocoaPods
    id: pods-cache
    uses: actions/cache@v2
    with:
      path: ${{ inputs.pod-path }}
      key: pods-${{ inputs.lock-hash }}
  - name: Install CocoaPods deps
    # Anyway, execute pod install to generate xcworkspace
    run: pod install --repo-update