name: 'Setup node and React Native CLI'
description: 'Setup node and React Native CLI'
author: 'okta'

inputs:
  node-version:
    description: 'Node version'
    required: false
    default: 16

runs:
  using: "composite"
  steps:
  - name: Setup node
    uses: actions/setup-node@v2
    with:
      node-version: ${{ inputs.node-version }}
  - name: Install React Native CLI
    run: npm install -g react-native-cli
    shell: bash